[package]
name = "acs"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = { version = "0.18.0", features = ["rayon"] }
ouroboros = "0.18.5"
rand = "0.9.2"
rayon = "1.11.0"
regex = "1.11.2"
