[package]
name = "acs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
indicatif = { version = "0.18.0", features = ["rayon"] }
rand = "0.9.2"
rayon = "1.11.0"
regex = "1.11.2"
